// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzfDW3NLsh3XeiIM-1G9OsQ7hcoy9reaM',
    appId: '1:547588597291:web:8bc223cbfbc77dcdfbac6e',
    messagingSenderId: '547588597291',
    projectId: 'power-path-43b00',
    authDomain: 'power-path-43b00.firebaseapp.com',
    storageBucket: 'power-path-43b00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo6EHx0oG0XB_k8o8K75zLH-fNd4owLis',
    appId: '1:592752258908:android:2c5931ec7d6c7ec9dddb99',
    messagingSenderId: '592752258908',
    projectId: 'power-path-c1bb4',
    storageBucket: 'power-path-c1bb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHDoau5rkajnvnvSjGMUuJ9VfAzsw7a_Q',
    appId: '1:592752258908:ios:8db78b343ba1808fdddb99',
    messagingSenderId: '592752258908',
    projectId: 'power-path-c1bb4',
    storageBucket: 'power-path-c1bb4.firebasestorage.app',
    iosBundleId: 'com.example.powerPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHaNx8zLvOl1jKaZaolr7LLY5Mvbb1CgA',
    appId: '1:547588597291:ios:c1a7a3d3618aec63fbac6e',
    messagingSenderId: '547588597291',
    projectId: 'power-path-43b00',
    storageBucket: 'power-path-43b00.firebasestorage.app',
    iosBundleId: 'com.example.powerPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzfDW3NLsh3XeiIM-1G9OsQ7hcoy9reaM',
    appId: '1:547588597291:web:5bd78047e4e4c6d9fbac6e',
    messagingSenderId: '547588597291',
    projectId: 'power-path-43b00',
    authDomain: 'power-path-43b00.firebaseapp.com',
    storageBucket: 'power-path-43b00.firebasestorage.app',
  );
}